name: "Terraform CI/CD"

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      action:
        description: 'Accion a ejecutar en Terraform'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    name: "Terraform Execution"
    runs-on: ubuntu-latest
    permissions:
     id-token: write   # Obligatorio para solicitar el token JWT a GitHub
     contents: read


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      # 1. Autenticar primero para tener acceso a S3 y DynamoDB
    
      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::374320036543:role/GitHubActionsTerraformRole
          aws-region: eu-west-1


      # 2. Comprobaciones de sintaxis e inicialización
      - name: Check code formatting
        run: terraform fmt -check -recursive

      - name: Initialize Terraform
        run: terraform init

      - name: Validate syntax
        run: terraform validate

      # 3. Escaneo estático de seguridad (Trivy)
      - name: Run Trivy IaC Security Scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'config'
          scan-ref: '.'
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '0'

      # 4. Planificación y despliegue
      - name: Run Terraform Plan
        if: "${{ github.event.inputs.action != 'destroy' }}"
        run: terraform plan -input=false

      - name: Run Terraform Apply
        if: "${{ github.event_name == 'push' || github.event.inputs.action == 'apply' }}"
        run: terraform apply -auto-approve -input=false

      - name: Run Terraform Destroy
        if: "${{ github.event.inputs.action == 'destroy' }}"
        run: terraform destroy -auto-approve -input=false