name: "Terraform CI/CD Multi-Environment"

"on":
  push:
    branches: [uat, pro]
  pull_request:
    branches: [uat, pro]
  workflow_dispatch:
    inputs:
      environment:
        description: "Entorno de despliegue"
        required: true
        default: "uat"
        type: choice
        options:
          - uat
          - pro
      action:
        description: "Accion a ejecutar"
        required: true
        default: "apply"
        type: choice
        options:
          - plan
          - apply
          - destroy

jobs:
  # -------------------------------------------------------------------
  # 1. PLANIFICACIÓN Y VALIDACIÓN (No requiere aprobación previa)
  # -------------------------------------------------------------------
  terraform-plan:
    name: "Terraform Plan & Scan"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write

    outputs:
      target_env: ${{ steps.set-env.outputs.TARGET_ENV }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Target Environment
        id: set-env
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            ENV="${{ github.event.inputs.environment }}"
          elif [ "${{ github.event_name }}" = "pull_request" ]; then
            ENV="${{ github.base_ref }}"
          else
            ENV="${{ github.ref_name }}"
          fi
          echo "TARGET_ENV=${ENV}" >> "$GITHUB_OUTPUT"
          echo "Ambiente seleccionado: ${ENV}"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::374320036543:role/GitHubActionsTerraformRole
          aws-region: eu-west-1

      - name: Check code formatting
        run: terraform fmt -check -recursive

      - name: Run Trivy IaC Security Scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: "config"
          scan-ref: "."
          format: "table"
          severity: "CRITICAL,HIGH"
          exit-code: "0"

      - name: Initialize Terraform
        run: |
          terraform init \
            -backend-config=vars/${{ steps.set-env.outputs.TARGET_ENV }}/state.config \
            -reconfigure

      - name: Validate syntax
        run: terraform validate

      - name: Run Terraform Plan
        if: github.event_name == 'pull_request' || (github.event_name == 'workflow_dispatch' && github.event.inputs.action != 'destroy') || github.event_name == 'push'
        run: |
          terraform plan \
            -var-file=vars/${{ steps.set-env.outputs.TARGET_ENV }}/${{ steps.set-env.outputs.TARGET_ENV }}.tfvars \
            -input=false

  # -------------------------------------------------------------------
  # 2. APLICACIÓN O DESTRUCCIÓN (Protegido con GitHub Environment)
  # -------------------------------------------------------------------
  terraform-apply:
    name: "Terraform Apply / Destroy"
    needs: terraform-plan
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.action != 'plan')
    environment: pro #${{ needs.terraform-plan.outputs.target_env }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::374320036543:role/GitHubActionsTerraformRole
          aws-region: eu-west-1

      - name: Initialize Terraform
        run: |
          terraform init \
            -backend-config=vars/${{ needs.terraform-plan.outputs.target_env }}/state.config \
            -reconfigure

      - name: Run Terraform Apply
        if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply')
        run: |
          terraform apply \
            -var-file=vars/${{ needs.terraform-plan.outputs.target_env }}/${{ needs.terraform-plan.outputs.target_env }}.tfvars \
            -auto-approve \
            -input=false

      - name: Run Terraform Destroy
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy'
        run: |
          terraform destroy \
            -var-file=vars/${{ needs.terraform-plan.outputs.target_env }}/${{ needs.terraform-plan.outputs.target_env }}.tfvars \
            -auto-approve \
            -input=false